### ISSUE TITLE
Botoanalytics not working

### ISSUE THREAD

**Issue by khushhalm** [Botanalyticsco/botanalytics#10]
Tried Alexa Sample, in the logs it says `2021-03-21T06:13:51.093Z 679e619f-4aa4-4de0-9b71-d551b6bed753 INFO [Botanalytics] Successfully logged incoming message.`
But on the Botoanalytics website, there is no data coming up.

Logs show that data is being sent
`INFO [Botanalytics] Logging enabled.`
`INFO [Botanalytics] Configuration: { baseUrl: 'https://api.botanalytics.co/v1/', debug: true }`
`INFO [Botanalytics] Successfully logged incoming message.`

**Comment by dacay** [comment]
We are working on a completely new version of Node SDK. Closing this.
