### ISSUE TITLE
Microsoft Bot Framework incompatability

### ISSUE THREAD

**Issue by sirtimbly** [Botanalyticsco/botanalytics#4]
When I installed the package and configured it per the instructions it did not work immediately. I had to do two extra things to work around this. 

Problem 1: The middleware property (for version 3.x SDK) is being used incorrectly. The property on middleware that is called is not called `receive` (though that makes sense) instead the received messages are passed into a method called `botbuilder`. 

Problem 2: is that the rest API returned a message about a missing "User ID" from the payload. Since the payload property in the code is called `message` and the parameter being passed in is actually `session` (the parent object) I think the library is passing the wrong object by default. 

Problem 3: the `next` function being passed as an argument into the middleware is never being called. So, the bot never continues processing. And all messages die inside the middleware function. 👎 

To successfully work around these 3 problems I was able to write shim functions in the middleware object like this. 

```ts
if (process.env.BOTANALYTICS_TOKEN) {
    const analytics = botanalytics.MicrosoftBotFramework(process.env.BOTANALYTICS_TOKEN);

    bot.use({
        botbuilder: (session, next) => {
            analytics.receive(session.message, next);
            next();
        },
        send: (event, next) => {
            analytics.send(event, next),
            next();
        },
    });
}
```

But, these could be fixed directly in the library. And the library could export an object that is compatible with the middleware definition to simplify the implementation in the `bot.use()` function.

**Comment by BeyhanEsen** [comment]
Thank you for reaching out @sirtimbly, its fixed in v2.4.3 which is out
