### ISSUE TITLE
ERROR:timestamp is required inside message parameter

### ISSUE THREAD

**Issue by benswinburne** [Botanalyticsco/botanalytics#5]
Presumably the object below should contain a timestamp property in order to resolve the message in the title. The `botbuilder` method uses a timestamp, but the `send` method does not.

```
body: {
 message: event,
 is_sender_bot: true
}
```

https://github.com/Botanalyticsco/botanalytics/blob/master/platforms/microsoft.js#L75

Unless I'm doing something wrong?

**Comment by BeyhanEsen** [comment]
Thanks @benswinburne , v2.4.7 fixes this problem.
